name: studentvueclient
description: a client library for the student vue grade system
version: 0.0.7
repository: https://github.com/StudentVue/StudentVue.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  xml: ^5.3.1
  html_unescape: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
